# Generated by Django 5.0.4 on 2024-04-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0001_initial'),
        ('PageRank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(default=0)),
                ('destination_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_transitions', to='CarritoApp.producto')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_transitions', to='CarritoApp.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'source_product', 'destination_product')},
            },
        ),
        migrations.DeleteModel(
            name='UserLinkTransition',
        ),
    ]
